SET FOREIGN_KEY_CHECKS=0

DROP TABLE IF EXISTS `Alumni` CASCADE
;

CREATE TABLE `Alumni`
(
	`alumniID` Integer NOT NULL,
	CONSTRAINT `PK_Alumni` PRIMARY KEY (`alumniID`)
)
;

SET FOREIGN_KEY_CHECKS=1
